server:
   tomcat:
     max-threads: 600
     max-connections: 200
     min-spare-threads: 300
     accept-count: 700

#LOGGING
logging:
  config: classpath:log4j2.xml
  level:
      org.springframework: WARN
      org.spring.springboot.dao: DEBUG

#spring config
spring:
    datasource:
      url: jdbc:mysql://125.65.83.240:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: project
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize：5
      minIdle：5
      maxActive：20
      maxWait：60000
      timeBetweenEvictionRunsMillis：60000
      minEvictableIdleTimeMillis：300000
      validationQuery：SELECT 1 FROM DUAL
      testWhileIdle：true
      testOnBorrow：false
      testOnReturn：false
      poolPreparedStatements：true
      maxPoolPreparedStatementPerConnectionSize：20
      filters：stat,wall,log4j
      connectionProperties：druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    mvc:
#        favicon:
#            enabled: false
# MyBatis
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.bp.po
    config-location: classpath:mybatis-config.xml
