server:
   tomcat:
     max-threads: 600
     max-connections: 200
     min-spare-threads: 300
     accept-count: 700

##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://125.65.83.240:3306/ad?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: project
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 50
    min-idle: 20
    max-idle: 50
    max-wait: 500
  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://192.168.248.198:3306/ad?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: project
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 50
    min-idle: 20
    max-idle: 50
    max-wait: 500

##mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.*.domain.pojo
  check-config-location: true
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:log4j2.xml


      
