server:
   tomcat:
     max-threads: 600
     max-connections: 200
     min-spare-threads: 300
     accept-count: 700

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.83.240:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: project
      password: 123456


##mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bp.*.domain.pojo
  check-config-location: true
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:log4j2.xml
  level:
    com.bp.mapper.CoreDao: DEBUG

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


      
