server:
   tomcat:
     max-threads: 600
     max-connections: 200
     min-spare-threads: 300
     accept-count: 700

#LOGGING
logging:
    config: classpath:logback.xml

#spring config
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://125.65.83.240:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: project
      password: 123456
#    mvc:
#        favicon:
#            enabled: false
# MyBatis
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    config: classpath:mybatis-config.xml